path: icu/datetimeevents.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: caregiver_id
    type: int64
  # db fields - times
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: itemid
    type: int64
  - name: value
    type: string
  - name: valueuom
    type: string
  - name: warning
    type: int64

join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)
    caregiver_id: col(caregiver_id)

events:
  - name: TIMESTAMP_OF
    columns:
      time: col(charttime)
      code:
        - col(itemid)
        - col(label)
    extension:
      datetime_value: col(value)
      datetime_uom: col(valueuom)
      warning: col(warning)
