path: hosp/hcpcsevents.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  # db fields - times
  - name: chartdate
    type: datetime
    params:
      format: "%Y-%m-%d"
  # db fields - values
  - name: hcpcs_cd
    type: string
  - name: seq_num
    type: int64
  - name: short_description
    type: string

join:
  - name: d_hcpcs
    path: hosp/d_hcpcs.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: code
        type: string
      - name: category
        type: int64
      - name: long_description
        type: string
    left_on:
      - hcpcs_cd
    right_on:
      - code
  - name: admissions
    path: hosp/admissions.csv.gz
    columns:
      # subject_id and extentions
      - name: hadm_id
        type: int64
      # db fields - times
      - name: dischtime
        type: datetime
        params:
          format: "%Y-%m-%d %H:%M:%S"
      # db fields - values
    both_on:
      - hadm_id

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)

events:
  - name: HCPCS
    columns:
      # TODO: move chartdate to end of day with callback
      time: col(chartdate)
      code:
        - col(hcpcs_cd)
        - col(long_description)
      extension:
        available_time: col(dischtime)
        seq_num: col(seq_num)
