path: icu/inputevents.csv.gz

columns:
  # subject_id and other ids
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: caregiver_id
    type: int64
  - name: orderid
    type: int64
  - name: linkorderid
    type: int64
  # db fields - times
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: endtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: itemid
    type: int64
  - name: amount
    type: float32
  - name: amountuom
    type: string
  - name: rate
    type: float32
  - name: rateuom
    type: string
  - name: ordercategoryname
    type: string
  - name: secondordercategoryname
    type: string
  - name: ordercomponenttypedescription
    type: string
  - name: ordercategorydescription
    type: string
  - name: patientweight
    type: float32
  - name: totalamount
    type: float32
  - name: totalamountuom
    type: string
  - name: isopenbag
    type: boolean
  - name: continueinnextdept
    type: boolean
  - name: statusdescription
    type: string
  - name: originalamount
    type: float32
  - name: originalrate
    type: float32

join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)
    caregiver_id: col(caregiver_id)
    orderid: col(orderid)
    linkorderid: col(linkorderid)

events:
  - name: INFUSION_START
    columns:
      time: col(starttime)
      available_time: max(col(storetime), col(starttime))
      # TODO: implement a max callback.
      code:
        - col(itemid)
        - col(label)
      extension:
        ordercategoryname: col(ordercategoryname)
        secondordercategoryname: col(secondordercategoryname)
        ordercomponenttypedescription: col(ordercomponenttypedescription)
        ordercategorydescription: col(ordercategorydescription)
        originalamount: col(originalamount)
        amountuom: col(amountuom)
        originalrate: col(originalrate)
        rateuom: col(rateuom)
        totalamount: col(totalamount)
        totalamountuom: col(totalamountuom)
        isopenbag: col(isopenbag)

  - name: INFUSION_END
    columns:
      time: col(endtime)
      available_time: max(col(storetime), col(endtime))
      code:
        - col(itemid)
        - col(label)
      text_value: col(statusdescription)
      extension:
        rate: col(rate)
        rateuom: col(rateuom)
        amount: col(amount)
        amountuom: col(amountuom)
        continueinnextdept: col(continueinnextdept)

  - name: SUBJECT_WEIGHT_AT_INFUSION
    columns:
      time: col(starttime)
      available_time: col(storetime)
      code:
        - const(kg)
      numeric_value: col(patientweight)
    filter:
      - deduplicate()
      # TODO: implement a filter that deduplicates multiple patient weights at the same timestamp.
