path: hosp/microbiologyevents.csv.gz

columns:
  # subject_id and extensions
  - name: microevent_id
    type: int64
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: micro_specimen_id
    type: int64
  - name: order_provider_id
    type: string
  # db fields - times
  - name: chartdate
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storedate
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: spec_itemid
    type: int64
  - name: spec_type_desc
    type: string
  - name: test_seq
    type: int64
  - name: test_itemid
    type: int64
  - name: test_name
    type: string
  - name: org_itemid
    type: int64
  - name: org_name
    type: string
  - name: isolate_num
    type: int64
  - name: quantity
    type: string
  - name: ab_itemid
    type: int64
  - name: ab_name
    type: string
  - name: dilution_text
    type: string
  - name: dilution_comparison
    type: string
  - name: dilution_value
    type: float32
  - name: interpretation
    type: string
  - name: comments
    type: string

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    microevent_id: col(microevent_id)
    micro_specimen_id: col(micro_specimen_id)
    order_provider_id: col(order_provider_id)

events:
  - name: MICROBIOLOGY_SPECIMEN
    columns:
      # TODO: move chartdate to end of day
      time: first_not_null(col(charttime), col(chartdate))
      code:
        - col(spec_itemid)
        - col(spec_type_desc)
      extension:
        available_time: first_not_null(col(charttime), col(chartdate))
    # TODO: deduplicate via a callback

  - name: MICROBIOLOGY_TEST
    columns:
      time: first_not_null(col(charttime), col(chartdate))
      code:
        - col(test_itemid)
        - col(test_name)
      extension:
        available_time: first_not_null(col(charttime), col(chartdate))
    # TODO: deduplicate via a callback

  - name: MICROBIOLOGY_ORGANISM
    columns:
      time: first_not_null(col(charttime), col(chartdate))
      code:
        - col(org_itemid)
        - col(org_name)
      numeric_value: col(quantity)
      text_value: col(comment)
      extension:
        available_time: first_not_null(col(storetime), col(storedate))
        isolate_num: col(isolate_num)
    # TODO: deduplicate via a callback

  - name: MICROBIOLOGY_SUSCEPTIBILITY
    columns:
      time: first_not_null(col(charttime), col(chartdate))
      code:
        - col(ab_itemid)
        - col(ab_name)
      text_value: col(interpretation)
      extension:
        available_time: first_not_null(col(storetime), col(storedate))
        dilution_text: col(dilution_text)
        dilution_comparison: col(dilution_comparison)
        dilution_value: col(dilution_value)
    filters:
      - drop_na(text_value)
