path: hosp/prescriptions.csv.gz

columns:
  # subject_id and extentions
  - name: hadm_id # should be identical field in pharmacy
    type: int64
  - name: subject_id  # should be identical field in pharmacy
    type: int64
  # db fields - times
  - name: starttime # identical field in pharmacy
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: stoptime  # identical field in pharmacy
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: doses_per_24_hrs
    type: float32
  - name: dose_unit_rx
    type: string
  - name: dose_val_rx
    type: string
  - name: drug
    type: string
  - name: drug_type
    type: string
  - name: form_rx
    type: string
  - name: form_unit_disp
    type: string
  - name: form_val_disp
    type: string
  - name: formulary_drug_cd
    type: string
  - name: gsn # Generic Sequence Number
    type: string
  - name: ndc # National Drug Code
    type: string
  - name: order_provider_id
    type: string
  - name: pharmacy_id # unique id in pharmacy table
    type: int64
  - name: prod_strength
    type: string
  - name: poe_id  # orders
    type: string
  - name: poe_seq
    type: int64
  - name: route # identical field in pharmacy
    type: string

join:
  - name: poe
    path: hosp/poe.csv.gz
    columns:
      - name: poe_id
        type: string
      - name: poe_seq
        type: int64
      # db fields - times
      - name: ordertime
        type: datetime
        params:
          format: "%Y-%m-%d %H:%M:%S"
    both_on:
      - poe_id
      - poe_seq

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    poe_id: col(poe_id)
    poe_seq: col(poe_seq)
    pharmacy_id: col(pharmacy_id)
    order_provider_id: col(order_provider_id)

events:
  - name: MEDICATION_ORDER
    columns:
      time: col(ordertime)
      available_time: col(ordertime)
      code:
        - col(drug)
      text_value: col(prod_strength)
      extension:
        prescribed_start: col(starttime)
        prescribed_end: col(stoptime)
        ndc: col(ndc)
        drug_type: col(drug_type)
        form: col(form_rx)
        dose: col(dose_val_rx)
        dose_uom: col(dose_unit_rx)
        route: col(route)
        # NOTE: some columns are omitted for now. Maybe revisited later if they are required downstream
