path: icu/procedureevents.csv.gz

columns:
  # subject_id and extensions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: caregiver_id
    type: int64
  - name: orderid
    type: int64
  - name: linkorderid
    type: int64
  # db fields - times
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: endtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      strict: false
  # db fields - values
  - name: itemid
    type: int64
  - name: value
    type: float32
  - name: valueuom
    type: string
  - name: location
    type: string
  - name: locationcategory
    type: string
  - name: ordercategoryname
    type: string
  - name: ordercategorydescription
    type: string
  - name: patientweight
    type: float32
  - name: isopenbag
    type: int64
  - name: continueinnextdept
    type: int64
  - name: statusdescription
    type: string
  - name: originalamount
    type: float32
  - name: originalrate
    type: float32


join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extensions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)
    caregiver_id: col(caregiver_id)
    orderid: col(orderid)
    linkorderid: col(linkorderid)

events:
  - name: PROCEDURE_START
    columns:
      time: col(starttime)
      code:
        - col(itemid)
        - col(label)
    extension:
      location: col(location)
      locationcategory: col(locationcategory)
      ordercategoryname: col(ordercategoryname)
      ordercategorydescription: col(ordercategorydescription)
      isopenbag: col(isopenbag)

  - name: PROCEDURE_END
    columns:
      time: col(endtime)
      code:
        - col(itemid)
        - col(label)
      text_value: col(statusdescription)
    extension:
      value: col(value)
      valueuom: col(valueuom)
      continueinnextdept: col(continueinnextdept)
    # TODO: add a filter for valueuom != "None"

  - name: SUBJECT_WEIGHT_AT_PROCEDURE
    columns:
      time: col(starttime)
      code:
        - const("kg")
      numeric_value: col(patientweight)
