path: hosp/transfers.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: transfer_id
    type: int64
  # db fields - times
  - name: intime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: outtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: eventtype
    type: string
  - name: careunit
    type: string

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    transfer_id: col(transfer_id)

events:
  - name: TRANSFER_TO
    time: col(intime)
    columns:
      code:
        - col(eventtype)
        - col(careunit)
      extension:
        available_time: col(intime)
