type: simple
mappings:
  - pattern:
      table: inputevents
      event: INFUSION_START
      code: (30043(//.*)?|30125(//.*)?|30307(//.*)?)
    columns: &id001
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (30043(//.*)?|30125(//.*)?|30307(//.*)?)
    columns: *id001
  - pattern:
      table: inputevents
      event: INFUSION_START
      code: (221662(//.*)?)
    columns: &id002
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (221662(//.*)?)
    columns: *id002
