type: simple
mappings:
  - pattern:
      table: admissions
      event: ED_REGISTRATION
      code: hospital_expire_flag
    columns: &id001
      numeric_value: col(hospital_expire_flag)
      text_value: col(hospital_expire_flag)
  - pattern:
      table: admissions
      event: ED_OUT
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: HOSPITAL_ADMISSION
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: INSURANCE
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: LANGUAGE
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: MARITAL_STATUS
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: ETHNICITY
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: HOSPITAL_DISCHARGE
      code: hospital_expire_flag
    columns: *id001
  - pattern:
      table: admissions
      event: MEDS_DEATH
      code: hospital_expire_flag
    columns: *id001
