type: simple
mappings:
  - pattern:
      table: chartevents
      event: CHART
      code: (1\.0\ ET/Trach(//.*)?|No\ Response\-ETT(//.*)?)
    columns:
      numeric_value: const(1)
      text_value: const("true")
