name: Concept
version: 1.0.0

config_files:
  - path: /workspaces/config/concept
    # includes:
    #   - antibiotics.1.0.0

config:
  extraction_step: Extraction
  dataset_configs:
    - name: mimic-iv
      path: /workspaces/config/mimic-iv/3.1/concept/
    - name: eicu-crd
      path: /workspaces/config/eicu-crd/2.0/concept/
    - name: nwicu
      path: /workspaces/config/nwicu/0.1.0/concept/
