name: Concept
version: 1.0.0
overwrite: true

config_files:
  - path: /workspaces/config/concepts
    # includes:
    #   - antibiotics.1.0.0

config:
  extraction_step: Extraction
  dataset_configs:
    - name: mimic-iv
      path: /workspaces/config/datasets/mimic-iv/3.1/mappings/
    - name: eicu-crd
      path: /workspaces/config/datasets/eicu-crd/2.0/mappings/
    - name: nwicu
      path: /workspaces/config/datasets/nwicu/0.1.0/mappings/
