name: Extraction
version: 1.0.0

config_files:
  - path: /workspaces/config/dataset/mimic-iv/3.1/dataset/
    # includes:
    #   - openicu.config.dataset.mimic-iv.3.1.prescriptions
    #   - openicu.config.dataset.mimic-iv.3.1.outputevents
    #   - openicu.config.dataset.mimic-iv.3.1.drgcodes
    #   - openicu.config.dataset.mimic-iv.3.1.services
    #   - openicu.config.dataset.mimic-iv.3.1.emar
    #   - openicu.config.dataset.mimic-iv.3.1.patients
    #   - openicu.config.dataset.mimic-iv.3.1.omr
    #   - openicu.config.dataset.mimic-iv.3.1.icustays
    #   - openicu.config.dataset.mimic-iv.3.1.datetimeevent
    #   - openicu.config.dataset.mimic-iv.3.1.hcpcsevents
    #   - openicu.config.dataset.mimic-iv.3.1.microbiologyevents
    #   - openicu.config.dataset.mimic-iv.3.1.procedureevents
    #   - openicu.config.dataset.mimic-iv.3.1.chartevents
    #   - openicu.config.dataset.mimic-iv.3.1.ingredientevents
    #   - openicu.config.dataset.mimic-iv.3.1.inputevents
    #   - openicu.config.dataset.mimic-iv.3.1.diagnoses_icd
    #   - openicu.config.dataset.mimic-iv.3.1.admissions
    #   - openicu.config.dataset.mimic-iv.3.1.labevents
  - path: /workspaces/config/dataset/nwicu/0.1.0/dataset/
    # includes:
    #   - openicu.config.dataset.nwicu.0.1.0.prescriptions
    #   - openicu.config.dataset.nwicu.0.1.0.patients
    #   - openicu.config.dataset.nwicu.0.1.0.icustays
    #   - openicu.config.dataset.nwicu.0.1.0.procedureevents
    #   - openicu.config.dataset.nwicu.0.1.0.chartevents
    #   - openicu.config.dataset.nwicu.0.1.0.admissions
    #   - openicu.config.dataset.nwicu.0.1.0.labevents
  - path: /workspaces/config/dataset/eicu-crd/2.0/dataset/
    # includes:
    #     - p'enicu.config.dataset.eicu.2.0.treatment
    #     - penicu.config.dataset.eicu.2.0.diagnosis
    #     - penicu.config.dataset.eicu.2.0.medication
    #     - penicu.config.dataset.eicu.2.0.intakeoutput
    #     - penicu.config.dataset.eicu.2.0.lab
    #     - penicu.config.dataset.eicu.2.0.respiratorycare
    #     - penicu.config.dataset.eicu.2.0.patient
    #     - penicu.config.dataset.eicu.2.0.careplangoal
    #     - penicu.config.dataset.eicu.2.0.vitalaperiodic
    #     - penicu.config.dataset.eicu.2.0.careplaninfectiousdisease
    #     - penicu.config.dataset.eicu.2.0.respiratorycharting
    #     - penicu.config.dataset.eicu.2.0.careplangeneral
    #     - penicu.config.dataset.eicu.2.0.nursecharting
    #     - penicu.config.dataset.eicu.2.0.nurseassessment
    #     - penicu.config.dataset.eicu.2.0.nursecare
    #     - penicu.config.dataset.eicu.2.0.infusiondrug
    #     - penicu.config.dataset.eicu.2.0.apachepatientresult
    #     - penicu.config.dataset.eicu.2.0.vitalperiodic
    #     - penicu.config.dataset.eicu.2.0.note
    #     - penicu.config.dataset.eicu.2.0.customlab
    #     - penicu.config.dataset.eicu.2.0.pasthistory
    #     - penicu.config.dataset.eicu.2.0.admissiondrug
    #     - penicu.config.dataset.eicu.2.0.careplaneol
    #     - penicu.config.dataset.eicu.2.0.allergy
    #     - penicu.config.dataset.eicu.2.0.apacheapsvar
    #     - penicu.config.dataset.eicu.2.0.admissiondx
    #     - penicu.config.dataset.eicu.2.0.apachepredvar
    #     - penicu.config.dataset.eicu.2.0.physicalexam
    #     - penicu.config.dataset.eicu.2.0.microlab'

config:
  data:
    - name: mimic-iv
      path: /workspaces/example/data/physionet.org/files/mimiciv/3.1
    - name: eicu-crd
      path: /workspaces/example/data/physionet.org/files/eicu-crd/2.0
    - name: nwicu
      path: /workspaces/example/data/physionet.org/files/nwicu-northwestern-icu/0.1.0
