name: Extraction
version: 1.0.0

config:
  data:
    - name: mimic-iv
      version: "3.1"
      path: /workspaces/example/data/physionet.org/files/mimiciv/3.1
      # includes:
      #   - openicu.config.table.mimic-iv.3.1.prescriptions
      #   - openicu.config.table.mimic-iv.3.1.outputevents
      #   - openicu.config.table.mimic-iv.3.1.drgcodes
      #   - openicu.config.table.mimic-iv.3.1.services
      #   - openicu.config.table.mimic-iv.3.1.emar
      #   - openicu.config.table.mimic-iv.3.1.patients
      #   - openicu.config.table.mimic-iv.3.1.omr
      #   - openicu.config.table.mimic-iv.3.1.icustays
      #   - openicu.config.table.mimic-iv.3.1.datetimeevent
      #   - openicu.config.table.mimic-iv.3.1.hcpcsevents
      #   - openicu.config.table.mimic-iv.3.1.microbiologyevents
      #   - openicu.config.table.mimic-iv.3.1.procedureevents
      #   - openicu.config.table.mimic-iv.3.1.chartevents
      #   - openicu.config.table.mimic-iv.3.1.ingredientevents
      #   - openicu.config.table.mimic-iv.3.1.inputevents
      #   - openicu.config.table.mimic-iv.3.1.diagnoses_icd
      #   - openicu.config.table.mimic-iv.3.1.admissions
      #   - openicu.config.table.mimic-iv.3.1.labevents
    - name: eicu-crd
      version: "2.0"
      path: /workspaces/example/data/physionet.org/files/eicu-crd/2.0
      # includes:
      # includes:
      #   - openicu.config.table.eicu-crd.2.0.treatment
      #   - openicu.config.table.eicu-crd.2.0.diagnosis
      #   - openicu.config.table.eicu-crd.2.0.medication
      #   - openicu.config.table.eicu-crd.2.0.intakeoutput
      #   - openicu.config.table.eicu-crd.2.0.lab
      #   - openicu.config.table.eicu-crd.2.0.respiratorycare
      #   - openicu.config.table.eicu-crd.2.0.patient
      #   - openicu.config.table.eicu-crd.2.0.careplangoal
      #   - openicu.config.table.eicu-crd.2.0.vitalaperiodic
      #   - openicu.config.table.eicu-crd.2.0.careplaninfectiousdisease
      #   - openicu.config.table.eicu-crd.2.0.respiratorycharting
      #   - openicu.config.table.eicu-crd.2.0.careplangeneral
      #   - openicu.config.table.eicu-crd.2.0.nursecharting
      #   - openicu.config.table.eicu-crd.2.0.nurseassessment
      #   - openicu.config.table.eicu-crd.2.0.nursecare
      #   - openicu.config.table.eicu-crd.2.0.infusiondrug
      #   - openicu.config.table.eicu-crd.2.0.apachepatientresult
      #   - openicu.config.table.eicu-crd.2.0.vitalperiodic
      #   - openicu.config.table.eicu-crd.2.0.note
      #   - openicu.config.table.eicu-crd.2.0.customlab
      #   - openicu.config.table.eicu-crd.2.0.pasthistory
      #   - openicu.config.table.eicu-crd.2.0.admissiondrug
      #   - openicu.config.table.eicu-crd.2.0.careplaneol
      #   - openicu.config.table.eicu-crd.2.0.allergy
      #   - openicu.config.table.eicu-crd.2.0.apacheapsvar
      #   - openicu.config.table.eicu-crd.2.0.admissiondx
      #   - openicu.config.table.eicu-crd.2.0.apachepredvar
      #   - openicu.config.table.eicu-crd.2.0.physicalexam
      #   - openicu.config.table.eicu-crd.2.0.microlab
