path: apachePredVar.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # GCS components
  - name: verbal
    type: int64
  - name: motor
    type: int64
  - name: eyes
    type: int64
  # demographics and outcomes
  - name: age
    type: int64
  - name: admitdiagnosis
    type: string
  - name: diedinhospital
    type: int64
  - name: dischargelocation
    type: string
  - name: readmit
    type: int64
  - name: electivesurgery
    type: int64
  - name: thrombolytics
    type: int64
  - name: diabetes
    type: int64
  # comorbidities
  - name: aids
    type: int64
  - name: hepaticfailure
    type: int64
  - name: lymphoma
    type: int64
  - name: metastaticcancer
    type: int64
  - name: leukemia
    type: int64
  - name: immunosuppression
    type: int64
  - name: cirrhosis
    type: int64
  # lab values
  - name: pao2
    type: float64
  - name: fio2
    type: float64
  - name: creatinine
    type: float64
  - name: ejectfx
    type: float64

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(admission_timestamp)
  extension:
    stay_id: col(patientunitstayid)

events:
  - name: APACHE_PRED_GCS_VERBAL
    columns:
      code:
        - const("GCS")
      numeric_value: col(verbal)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_PRED_GCS_MOTOR
    columns:
      code:
        - const("GCS")
      numeric_value: col(motor)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_PRED_GCS_EYES
    columns:
      code:
        - const("GCS")
      numeric_value: col(eyes)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_ADMIT_DIAGNOSIS
    columns:
      text_value: col(admitdiagnosis)
    filters:
      - drop_na(text_value)
  - name: APACHE_DIED_IN_HOSPITAL
    columns:
      numeric_value: col(diedinhospital)
  - name: APACHE_DISCHARGE_LOCATION
    columns:
      text_value: col(dischargelocation)
    filters:
      - drop_na(text_value)
  - name: APACHE_READMIT
    columns:
      numeric_value: col(readmit)
  - name: APACHE_ELECTIVE_SURGERY
    columns:
      numeric_value: col(electivesurgery)
  - name: APACHE_THROMBOLYTICS
    columns:
      numeric_value: col(thrombolytics)
  - name: APACHE_DIABETES
    columns:
      numeric_value: col(diabetes)
  - name: APACHE_AIDS
    columns:
      numeric_value: col(aids)
  - name: APACHE_HEPATIC_FAILURE
    columns:
      numeric_value: col(hepaticfailure)
  - name: APACHE_LYMPHOMA
    columns:
      numeric_value: col(lymphoma)
  - name: APACHE_METASTATIC_CANCER
    columns:
      numeric_value: col(metastaticcancer)
  - name: APACHE_LEUKEMIA
    columns:
      numeric_value: col(leukemia)
  - name: APACHE_IMMUNOSUPPRESSION
    columns:
      numeric_value: col(immunosuppression)
  - name: APACHE_CIRRHOSIS
    columns:
      numeric_value: col(cirrhosis)
  - name: APACHE_PRED_PAO2
    columns:
      numeric_value: col(pao2)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_PRED_FIO2
    columns:
      numeric_value: col(fio2)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_PRED_CREATININE
    columns:
      numeric_value: col(creatinine)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_EJECTION_FRACTION
    columns:
      numeric_value: col(ejectfx)
    filters:
      - drop_na(numeric_value)
