path: apacheApsVar.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # db fields - binary flags
  - name: intubated
    type: int64
  - name: vent
    type: int64
  - name: dialysis
    type: int64
  # GCS components
  - name: eyes
    type: int64
  - name: motor
    type: int64
  - name: verbal
    type: int64
  # lab/vital values
  - name: urine
    type: float64
  - name: wbc
    type: float64
  - name: temperature
    type: float64
  - name: respiratoryrate
    type: float64
  - name: sodium
    type: int64
  - name: heartrate
    type: int64
  - name: meanbp
    type: int64
  - name: ph
    type: float64
  - name: hematocrit
    type: float64
  - name: creatinine
    type: float64
  - name: albumin
    type: float64
  - name: pao2
    type: float64
  - name: pco2
    type: float64
  - name: bun
    type: int64
  - name: glucose
    type: int64
  - name: bilirubin
    type: float64
  - name: fio2
    type: float64

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(admission_timestamp)
  extension:
    stay_id: col(patientunitstayid)

events:
  - name: APACHE_APS_INTUBATED
    columns:
      numeric_value: col(intubated)
  - name: APACHE_APS_VENT
    columns:
      numeric_value: col(vent)
  - name: APACHE_APS_DIALYSIS
    columns:
      numeric_value: col(dialysis)
  - name: APACHE_APS_GCS_EYES
    columns:
      code:
        - const("GCS")
      numeric_value: col(eyes)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_GCS_MOTOR
    columns:
      code:
        - const("GCS")
      numeric_value: col(motor)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_GCS_VERBAL
    columns:
      code:
        - const("GCS")
      numeric_value: col(verbal)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_URINE
    columns:
      code:
        - const("mL")
      numeric_value: col(urine)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_WBC
    columns:
      numeric_value: col(wbc)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_TEMPERATURE
    columns:
      numeric_value: col(temperature)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_RESPIRATORY_RATE
    columns:
      numeric_value: col(respiratoryrate)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_SODIUM
    columns:
      numeric_value: col(sodium)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_HEART_RATE
    columns:
      numeric_value: col(heartrate)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_MEAN_BP
    columns:
      numeric_value: col(meanbp)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_PH
    columns:
      numeric_value: col(ph)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_HEMATOCRIT
    columns:
      numeric_value: col(hematocrit)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_CREATININE
    columns:
      numeric_value: col(creatinine)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_ALBUMIN
    columns:
      numeric_value: col(albumin)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_PAO2
    columns:
      numeric_value: col(pao2)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_PCO2
    columns:
      numeric_value: col(pco2)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_BUN
    columns:
      numeric_value: col(bun)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_GLUCOSE
    columns:
      numeric_value: col(glucose)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_BILIRUBIN
    columns:
      numeric_value: col(bilirubin)
    filters:
      - drop_na(numeric_value)
  - name: APACHE_APS_FIO2
    columns:
      numeric_value: col(fio2)
    filters:
      - drop_na(numeric_value)
