path: note.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # db fields - times
  - name: noteoffset
    type: int64
  # db fields - values
  - name: notetype
    type: string
  - name: notepath
    type: string
  - name: notevalue
    type: string
  - name: notetext
    type: string

post_callbacks:
  - add_offset(admission_timestamp, noteoffset, event_timestamp)

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(event_timestamp)
  extension:
    stay_id: col(patientunitstayid)

events:
  - name: note
    columns:
      code:
        - col(notetype)
        - col(notepath)
      text_value: col(notetext)
    filters:
      - drop_na(notetext)
