path: nurseCharting.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # db fields - times
  - name: nursingchartoffset
    type: int64
  # db fields - values
  - name: nursingchartcelltypecat
    type: string
  - name: nursingchartcelltypevallabel
    type: string
  - name: nursingchartcelltypevalname
    type: string
  - name: nursingchartvalue
    type: string

post_callbacks:
  - add_offset(admission_timestamp, nursingchartoffset, event_timestamp)

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(event_timestamp)
  extension:
    stay_id: col(patientunitstayid)

events:
  - name: nursingchartevent
    columns:
      code:
        - col(nursingchartcelltypecat)
        - col(nursingchartcelltypevallabel)
        - col(nursingchartcelltypevalname)
      text_value: col(nursingchartvalue)
    filters:
      - drop_na(nursingchartvalue)
