path: respiratoryCare.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  - name: respcareid
    type: int64
  # db fields - times
  - name: respcarestatusoffset
    type: int64
  - name: ventstartoffset
    type: int64
  - name: ventendoffset
    type: int64
  # db fields - values
  - name: airwaytype
    type: string
  - name: airwaysize
    type: string
  - name: airwayposition
    type: string
  - name: cuffpressure
    type: float64

post_callbacks:
  - add_offset(admission_timestamp, respcarestatusoffset, enter_timestamp)
  - add_offset(admission_timestamp, ventstartoffset, ventstart_timestamp)
  - add_offset(admission_timestamp, ventendoffset, ventend_timestamp)

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  extension:
    stay_id: col(patientunitstayid)
    respcare_id: col(respcareid)

events:
  - name: VENTILATION_START
    columns:
      time: col(ventstart_timestamp)
      code:
        - col(airwaytype)
      extension:
        available_time: col(enter_timestamp)
        airwaysize: col(airwaysize)
        airwayposition: col(airwayposition)
        cuffpressure: col(cuffpressure)

  - name: VENTILATION_END
    columns:
      time: col(ventend_timestamp)
      code:
        - col(airwaytype)
    # TODO: drop ventendoffset == 0
    # TODO: this currently does not consider cases where ventend_timestamp < enter_timestamp
