path: respiratoryCare.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # db fields - times
  - name: respcarestatusoffset
    type: int64
  - name: ventstartoffset
    type: int64
  - name: ventendoffset
    type: int64
  # db fields - values
  - name: airwaytype
    type: string
  - name: airwaysize
    type: string
  - name: airwayposition
    type: string
  - name: cuffpressure
    type: float32

post_callbacks:
  - add_offset(admission_timestamp, respcarestatusoffset, event_timestamp)
  - add_offset(admission_timestamp, ventstartoffset, ventstart_timestamp)
  - add_offset(admission_timestamp, ventendoffset, ventend_timestamp)

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(event_timestamp)
  extension:
    hadm_id: const(None)
    stay_id: col(patientunitstayid)

events:
  - name: airwaytype
    columns:
      text_value: col(airwaytype)
    filters:
      - drop_na(text_value)
  - name: airwaysize
    columns:
      text_value: col(airwaysize)
    filters:
      - drop_na(text_value)
  - name: airwayposition
    columns:
      text_value: col(airwayposition)
    filters:
      - drop_na(text_value)
  - name: cuffpressure
    columns:
      numeric_value: col(cuffpressure)
    filters:
      - drop_na(numeric_value)
  - name: ventstart
    columns:
      time: col(ventstart_timestamp)
      code:
        - const("ventstart_offset_min")
      numeric_value: col(ventstartoffset)
    filters:
      - drop_na(numeric_value)
  - name: ventend
    columns:
      time: col(ventend_timestamp)
      code:
        - const("ventend_offset_min")
      numeric_value: col(ventendoffset)
    filters:
      - drop_na(numeric_value)
