path: vitalAperiodic.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  - name: vitalaperiodicid
    type: int64
  # db fields - times
  - name: observationoffset
    type: int64
  # db fields - values
  - name: noninvasivesystolic
    type: float32
  - name: noninvasivediastolic
    type: float32
  - name: noninvasivemean
    type: float32
  - name: paop
    type: float32
  - name: cardiacoutput
    type: float32
  - name: cardiacinput
    type: float32
  - name: svr
    type: float32
  - name: svri
    type: float32
  - name: pvr
    type: float32
  - name: pvri
    type: float32

post_callbacks:
  - add_offset(admission_timestamp, observationoffset, output=event_timestamp)

join:
  - name: patient
    path: patient.csv.gz
    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64
    both_on:
      - patientunitstayid
    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset, "minutes", output=admission_timestamp)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(event_timestamp)
  extension:
    stay_id: col(patientunitstayid)
    vitalaperiodic_id: col(vitalaperiodicid)
    available_time: col(event_timestamp)

events:
  # TODO: can we preface all of these with VITAL//
  - name: NON_INVASIVE_SYSTOLIC_BLOOD_PRESSURE
    columns:
      numeric_value: col(noninvasivesystolic)
    filters:
      - drop_na(numeric_value)
  - name: NON_INVASIVE_DIASTOLIC_BLOOD_PRESSURE
    columns:
      numeric_value: col(noninvasivediastolic)
    filters:
      - drop_na(numeric_value)
  - name: NON_INVASIVE_MEAN_BLOOD_PRESSURE
    columns:
      numeric_value: col(noninvasivemean)
    filters:
      - drop_na(numeric_value)
  - name: PULMONARY_ARTERY_OCCLUSION_PRESSURE
    columns:
      numeric_value: col(paop)
    filters:
      - drop_na(numeric_value)
  - name: CARDIAC_OUTPUT
    columns:
      numeric_value: col(cardiacoutput)
    filters:
      - drop_na(numeric_value)
  - name: CARDIAC_INPUT
    columns:
      numeric_value: col(cardiacinput)
    filters:
      - drop_na(numeric_value)
  - name: SYSTEMIC_VASCULAR_RESISTANCE
    columns:
      numeric_value: col(svr)
    filters:
      - drop_na(numeric_value)
  - name: SYSTEMIC_VASCULAR_RESISTANCE_INDEX
    columns:
      numeric_value: col(svri)
    filters:
      - drop_na(numeric_value)
  - name: PULMONARY_VASCULAR_RESISTANCE
    columns:
      numeric_value: col(pvr)
    filters:
      - drop_na(numeric_value)
  - name: PULMONARY_VASCULAR_RESISTANCE_INDEX
    columns:
      numeric_value: col(pvri)
    filters:
      - drop_na(numeric_value)
