type: simple
mappings:
  - pattern:
      table: patient
      event: GENDER
      code: hospitaldischargestatus
    columns: &id001
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: patient
      event: ICU_ADMISSION
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: MEDS_BIRTH
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: ETHNICITY
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_HEIGHT
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_WEIGHT
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: ICU_DISCHARGE
      code: hospitaldischargestatus
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_WEIGHT
      code: hospitaldischargestatus
    columns: *id001
