type: simple
mappings:
  - pattern:
      table: patient
      event: GENDER
      code: admissionweight
    columns: &id001
      numeric_value: col(admissionweight)
      text_value: col(admissionweight)
  - pattern:
      table: patient
      event: ICU_ADMISSION
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: MEDS_BIRTH
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: ETHNICITY
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_HEIGHT
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_WEIGHT
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: ICU_DISCHARGE
      code: admissionweight
    columns: *id001
  - pattern:
      table: patient
      event: SUBJECT_WEIGHT
      code: admissionweight
    columns: *id001
