type: simple
mappings:
  - pattern:
      table: vitalperiodic
      event: HEART_RATE
      code: systemicsystolic
    columns: &id001
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: vitalperiodic
      event: TEMPERATURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: O2_SATURATION_PULSE_OXIMETRY
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: RESPIRATORY_RATE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: CENTRAL_VENOUS_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: CENTRAL_VENOUS_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ETCO2
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: SYSTOLIC_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: DIASTOLIC_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: MEAN_INVASIVE_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_SYSTOLIC_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_DIASTOLIC_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_MEAN_BLOOD_PRESSURE
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_1
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_2
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_3
      code: systemicsystolic
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: INTRACRANIAL_PRESSURE
      code: systemicsystolic
    columns: *id001
