type: simple
mappings:
  - pattern:
      table: chexpert
      event: CXR_ATELECTASIS
      code: (CXR_ATELECTASIS(//.*)?)
    columns:
      numeric_value: col(numeric_value)
  - pattern:
      table: negbio
      event: CXR_ATELECTASIS
      code: (CXR_ATELECTASIS(//.*)?)
    columns:
      numeric_value: col(numeric_value)
