# HiRID v1.1.1 -- observations variableid(s) 300, 310 [ricu resp]
type: simple
mappings:
  - pattern:
      table: observations
      event: OBSERVATION
      code: "(300|310)(//.*)?$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
