path: diagnosis.csv.gz

columns:
  # subject_id and extensions
  - name: patientunitstayid
    type: int64
  # db fields - times
  - name: diagnosisoffset
    type: int64
  # db fields - values
  - name: diagnosisstring
    type: string
  - name: icd9code
    type: string
  - name: diagnosispriority
    type: string

join:
  - name: patient
    path: patient.csv.gz

    columns:
      - name: patienthealthsystemstayid
        type: int64
      - name: patientunitstayid
        type: int64
      - name: hospitaladmitoffset
        type: int64
      - name: hospitaladmittime24
        type: string
      - name: hospitaldischargeyear
        type: int64

    both_on:
      - patientunitstayid

    callbacks:
      - to_datetime(hospitaldischargeyear, 1, 1, hospitaladmittime24, hospitaladmitoffset * -1, "minutes", output=admission_timestamp)

    post_join_callbacks:
      - add_offset(admission_timestamp, diagnosisoffset, output=event_timestamp)

transformations:
  - split_explode(icd9code)

event_defaults:
  subject_id: col(patienthealthsystemstayid)
  time: col(event_timestamp)
  extension:
    stay_id: col(patientunitstayid)

events:
  - name: DIAGNOSIS
    columns:
      code:
        - const(ICD)
        - col(icd9code)
      text_value: col(diagnosisstring)
      extension:
        diagnosispriority: col(diagnosispriority)
    filters:
      - drop_na(diagnosisstring)
