type: simple
mappings:
  - pattern:
      table: chartevents
      event: result
      code: (220227//Arterial O2 Saturation)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: labevents
      event: result
      code: (50817//Oxygen Saturation)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
