# AUMCdb (OMOP CDM 5.4 via AMSTEL) -- maps AUMC items:
#   8874  Ademfrequentie Monitor -> OMOP measurement_concept_id 3024171
#   12266 Ademfreq.              -> OMOP measurement_concept_id 3007646
type: simple
mappings:
  - pattern:
      table: measurement
      event: MEASUREMENT
      code: "(3024171//Ademfrequentie Monitor//None|3007646//Ademfreq\\.///min)$"
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
