type: simple
mappings:
  - pattern:
      table: inputevents
      event: INFUSION_START
      code: (220950(//.*)?|228140(//.*)?|220952(//.*)?)
    columns: &id001
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (220950(//.*)?|228140(//.*)?|220952(//.*)?)
    columns: *id001
