path: hosp/omr.csv.gz

columns:
  # subject_id and extentions
  - name: subject_id
    type: int64
  # db fields - times
  - name: chartdate
    type: datetime
    # params:
    #   format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: result_name
    type: string
  - name: result_value
    type: string
  - name: seq_num
    type: int64

events:
  - name: result
    columns:
      subject_id: col(subject_id)
      time: col(chartdate)
      code:
        - col(result_name)
      text_value: col(result_value)
      numeric_value: col(seq_num)
      extension:
