"""YAIB dynamic variable list and RICU abbreviation -> OpenICU concept mapping."""

from __future__ import annotations

DYNAMIC_VARS: list[str] = [
    "alb", "alp", "alt", "ast", "be", "bicar", "bili", "bili_dir",
    "bnd", "bun", "ca", "cai", "ck", "ckmb", "cl", "crea", "crp",
    "dbp", "fgn", "fio2", "glu", "hgb", "hr", "inr_pt", "k", "lact",
    "lymph", "map", "mch", "mchc", "mcv", "methb", "mg", "na", "neut",
    "o2sat", "pco2", "ph", "phos", "plt", "po2", "ptt", "resp", "sbp",
    "temp", "tnt", "urine", "wbc",
]

RICU_TO_OPENICU: dict[str, str] = {
    "alb": "albumin",
    "alp": "alkaline_phosphatase",
    "alt": "alanine_aminotransferase",
    "ast": "aspartate_aminotransferase",
    "be": "base_excess",
    "bicar": "bicarbonate",
    "bili": "total_bilirubin",
    "bili_dir": "bilirubin_direct",
    "bnd": "band_form_neutrophils",
    "bun": "blood_urea_nitrogen",
    "ca": "calcium",
    "cai": "calcium_ionized",
    "ck": "creatine_kinase",
    "ckmb": "creatine_kinase_MB",
    "cl": "chloride",
    "crea": "creatinine",
    "crp": "C_reactive_protein",
    "dbp": "diastolic_blood_pressure",
    "fgn": "fibrinogen",
    "fio2": "fraction_of_inspired_oxygen",
    "glu": "glucose",
    "hgb": "hemoglobin",
    "hr": "heart_rate",
    "inr_pt": "prothrombin_time_international_normalized_ratio",
    "k": "potassium",
    "lact": "lactate",
    "lymph": "lymphocytes",
    "map": "mean_arterial_pressure",
    "mch": "mean_corpuscular_hemoglobin",
    "mchc": "mean_corpuscular_hemoglobin_concentration",
    "mcv": "mean_corpuscular_volume",
    "methb": "methemoglobin",
    "mg": "magnesium",
    "na": "sodium",
    "neut": "neutrophils",
    "o2sat": "oxygen_saturation",
    "pco2": "CO2_partial_pressure",
    "ph": "pH_of_blood",
    "phos": "phosphate",
    "plt": "platelet_count",
    "po2": "O2_partial_pressure",
    "ptt": "partial_thromboplastin_time",
    "resp": "respiratory_rate",
    "sbp": "systolic_blood_pressure",
    "temp": "temperature",
    "tnt": "troponin_t",
    "urine": "urine_output",
    "wbc": "white_blood_cell_count",
}
