name: GCS_eye
version: 1.0.0
unit: None

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (220739//GCS - Eye Opening)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
