type: simple
mappings:
  - pattern:
      table: vitalperiodic
      event: HEART_RATE
      code: systemicmean
    columns: &id001
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: vitalperiodic
      event: TEMPERATURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: O2_SATURATION_PULSE_OXIMETRY
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: RESPIRATORY_RATE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: CENTRAL_VENOUS_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: CENTRAL_VENOUS_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ETCO2
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: SYSTOLIC_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: DIASTOLIC_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: MEAN_INVASIVE_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_SYSTOLIC_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_DIASTOLIC_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: PULMONARY_ARTERY_MEAN_BLOOD_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_1
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_2
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: ST_SEGMENT_DEVIATION_LEAD_3
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalperiodic
      event: INTRACRANIAL_PRESSURE
      code: systemicmean
    columns: *id001
  - pattern:
      table: vitalaperiodic
      event: NON_INVASIVE_SYSTOLIC_BLOOD_PRESSURE
      code: noninvasivemean
    columns: &id002
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: vitalaperiodic
      event: NON_INVASIVE_DIASTOLIC_BLOOD_PRESSURE
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: NON_INVASIVE_MEAN_BLOOD_PRESSURE
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: PULMONARY_ARTERY_OCCLUSION_PRESSURE
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: CARDIAC_OUTPUT
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: CARDIAC_INPUT
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: SYSTEMIC_VASCULAR_RESISTANCE
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: SYSTEMIC_VASCULAR_RESISTANCE_INDEX
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: PULMONARY_VASCULAR_RESISTANCE
      code: noninvasivemean
    columns: *id002
  - pattern:
      table: vitalaperiodic
      event: PULMONARY_VASCULAR_RESISTANCE_INDEX
      code: noninvasivemean
    columns: *id002
