type: simple
mappings:
- pattern:
    table: infusiondrug
    event: INFUSION
    code: (?i)^phenylephrine.*\(mcg/kg/min\)$
  columns:
    numeric_value: col(numeric_value)
    text_value: col(text_value)
  filters:
  - drop_na(numeric_value)
