type: simple
mappings:
  - pattern:
      table: respiratorycharting
      event: RESPIRATORY_CHART
      code: ^respFlowCareData//RT Vent On/Off$
    columns:
      text_value: col(text_value)
    filters:
      - text_value == "Start"
