type: simple
mappings:
  - pattern:
      table: prescriptions
      event: result
      code: (aztreonam|bactrim|cephalexin|chloramphenicol|cipro|flagyl|metronidazole|nitrofurantoin|tazobactam|rifampin|sulfadiazine|timentin|trimethoprim|(amika|gentami|vanco)cin|(amoxi|ampi|dicloxa|naf|oxa|peni|pipera)cillin|(azithro|clarithro|erythro|clinda|strepto|tobra|vanco)mycin|cef(azolin|tazidime|adroxil|epime|otetan|otaxime|podoxime|uroxime)|(doxy|mino|tetra)cycline|(levofl|moxifl|ofl)oxacin|macro(bid|dantin)|(una|zo)syn)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents_mv
      event: result
      code: (225879//Levofloxacin|225877//Isoniazid|225840//Amikacin|225871//Foscarnet|225875//Gentamicin|225873//Gancyclovir|225798//Vancomycin|225848//Caspofungin|225895//Pyrazinamide|225863//Daptomycin|225898//Rifampin|225884//Metronidazole|225903//Valgancyclovir|225844//Atovaquone|225855//Ceftriaxone|225899//Bactrim (SMX/TMP)|225902//Tobramycin|225876//Imipenem/Cilastatin|225838//Ambisome|225842//Ampicillin|225853//Ceftazidime|225900//Dalfopristin/Quinupristin (Synercid)|225851//Cefepime|225881//Linezolid|225883//Meropenem|225893//Piperacillin/Tazobactam (Zosyn)|225868//Ethambutol|225885//Micafungin|225837//Acyclovir|227691//Keflex|225847//Aztreonam|225857//Chloroquine|225886//Moxifloxacin|225882//Mefloquine|225843//Ampicillin/Sulbactam (Unasyn)|225890//Penicillin G potassium|225897//Ribavirin|225888//Nafcillin|225845//Azithromycin|225850//Cefazolin|225862//Colistin|228003//Tamiflu|225865//Doxycycline|225905//Voriconazole|225889//Oxacillin|225896//Quinine|225869//Fluconazole|225860//Clindamycin|225859//Ciprofloxacin|225866//Erythromycin|225892//Piperacillin)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
