type: simple
mappings:
  - pattern:
      table: chartevents
      event: result
      code: (226253//SpO2 Desat Limit|220277//O2 saturation pulseoxymetry)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: chartevents
      event: result
      code: (50817//Oxygen Saturation)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: labevents
      event: result
      code: None
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
