type: simple
mappings:
  - pattern:
      table: inputevents_cv
      event: result
      code: ()
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents_cv
      event: result
      code: ()
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: inputevents_mv
      event: result
      code: (221749//Phenylephrine)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
