type: simple
mappings:
  - pattern:
      table: procedureevents_mv
      event: result
      code: (227194//Extubation|225468//Unplanned Extubation (patient-initiated)|225477//Unplanned Extubation (non-patient initiated))
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      table: chartevents
      event: result
      code: (226732//O2 Delivery Device(s))
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
