type: simple
mappings:
  - pattern:
      table: chartevents
      event: result
      code: (223849//Ventilator Mode|223848//Ventilator Type|224695//Peak Insp. Pressure|224697//Mean Airway Pressure|224705//P High (APRV)|224687//Minute Volume|224704//ATC %|224746//Transpulmonary Pressure (Exp. Hold)|224706//P Low (APRV)|224709//T Low (APRV)|224684//Tidal Volume (set)|224747//Transpulmonary Pressure (Insp. Hold)|224703//ZATC Tube \#|224685//Tidal Volume (observed)|224696//Plateau Pressure|224707//T High (APRV)|224701//PSV Level|224750//Nitric Oxide Tank Pressure|227187//Pinsp (Draeger only)|224700//Total PEEP Level|224702//PCV Level|220339//PEEP set|224419//Negative Insp. Force|224686//Tidal Volume (spontaneous)|224738//Inspiratory Time|226873//Inspiratory Ratio)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
