path: data/nw_hosp/diagnoses_icd.csv.gz

columns:
  # subject_id and extensions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64

  # db fields - times

  # db fields - values
  - name: seq_num
    type: int64
  - name: icd_code
    type: string
  - name: icd_version
    type: int64

join:
  - name: d_icd_diagnoses
    path: data/nw_hosp/d_icd_diagnoses.csv.gz
    columns:
      - name: icd_code
        type: string
      - name: icd_version
        type: int64
      - name: long_title
        type: string
    both_on:
      - icd_code
      - icd_version

  - name: admissions
    path: data/nw_hosp/admissions.csv.gz
    columns:
      - name: hadm_id
        type: int64
      - name: dischtime
        type: datetime
        params:
          format: "%Y-%m-%d %H:%M:%S"
    both_on:
      - hadm_id

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)

events:
  - name: DIAGNOSIS
    columns:
      time: col(dischtime)
      code:
        - const(ICD)
        - col(icd_version)
        - col(icd_code)
        - col(long_title)
      extension:
        available_time: col(dischtime)
        seq_num: col(seq_num)
