path: data/nw_hosp/prescriptions.csv.gz

columns:
  # subject_id and extensions
  - name: subject_id
    type: int64
  - name: hadm_id
    type: int64
  - name: pharmacy_id
    type: int64
  - name: poe_id
    type: string
  - name: poe_seq
    type: int64
  - name: order_provider_id
    type: string

  # db fields - times
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: stoptime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"

  # db fields - values
  - name: doses_per_24_hrs
    type: float32
  - name: dose_unit_rx
    type: string
  - name: dose_val_rx
    type: string
  - name: drug
    type: string
  - name: drug_type
    type: string
  - name: form_rx
    type: string
  - name: form_unit_disp
    type: string
  - name: form_val_disp
    type: string
  - name: formulary_drug_cd
    type: string
  - name: gsn
    type: string
  - name: ndc
    type: string
  - name: prod_strength
    type: string
  - name: route
    type: string

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    poe_id: col(poe_id)
    poe_seq: col(poe_seq)
    pharmacy_id: col(pharmacy_id)
    order_provider_id: col(order_provider_id)

events:
  - name: MEDICATION_ORDER
    columns:
      time: col(starttime)
      code:
        - col(drug)
      text_value: col(prod_strength)
      extension:
        available_time: col(starttime)
        prescribed_start: col(starttime)
        prescribed_end: col(stoptime)
        ndc: col(ndc)
        drug_type: col(drug_type)
        form: col(form_rx)
        dose: col(dose_val_rx)
        dose_uom: col(dose_unit_rx)
        route: col(route)
