name: antibiotics
version: 1.0.0
unit: None

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: prescriptions
      event: result
      code: (aztreonam|bactrim|cephalexin|chloramphenicol|cipro|flagyl|metronidazole|nitrofurantoin|tazobactam|rifampin|sulfadiazine|timentin|trimethoprim|(amika|gentami|vanco)cin|(amoxi|ampi|dicloxa|naf|oxa|peni|pipera)cillin|(azithro|clarithro|erythro|clinda|strepto|tobra|vanco)mycin|cef(azolin|tazidime|adroxil|epime|otetan|otaxime|podoxime|uroxime)|(doxy|mino|tetra)cycline|(levofl|moxifl|ofl)oxacin|macro(bid|dantin)|(una|zo)syn)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: inputevents
      event: result
      code: (225798//Vancomycin|225837//Acyclovir|225838//Ambisome|225840//Amikacin|225842//Ampicillin|225843//Ampicillin/Sulbactam (Unasyn)|225844//Atovaquone|225845//Azithromycin|225847//Aztreonam|225848//Caspofungin|225850//Cefazolin|225851//Cefepime|225853//Ceftazidime|225855//Ceftriaxone|225857//Chloroquine|225859//Ciprofloxacin|225860//Clindamycin|225862//Colistin|225863//Daptomycin|225865//Doxycycline|225866//Erythromycin|225868//Ethambutol|225869//Fluconazole|225871//Foscarnet|225873//Gancyclovir|225875//Gentamicin|225876//Imipenem/Cilastatin|225877//Isoniazid|225879//Levofloxacin|225881//Linezolid|225882//Mefloquine|225883//Meropenem|225884//Metronidazole|225885//Micafungin|225886//Moxifloxacin|225888//Nafcillin|225889//Oxacillin|225890//Penicillin G potassium|225892//Piperacillin|225893//Piperacillin/Tazobactam (Zosyn)|225895//Pyrazinamide|225896//Quinine|225897//Ribavirin|225898//Rifampin|225899//Bactrim (SMX/TMP)|225900//Dalfopristin/Quinupristin (Synercid)|225902//Tobramycin|225903//Valgancyclovir|225905//Voriconazole|227691//Keflex|228003//Tamiflu)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
