name: insulin
version: 1.0.0
unit: units/hr

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: inputevents
      event: result
      code: (223258//Insulin - Regular|223260//Insulin - Glargine)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
