default_order: 30
unassigned: warn

groups:
  hospital_admission:
    order: 10
    concepts:
      - hospital_admission

  icu_admission:
    order: 11
    concepts:
      - icu_admission

  demographics:
    order: 20
    concepts:
      - patient_admission_type
      - patient_age
      - patient_height
      - patient_sex
      - patient_weight

  derived_first_level:
    order: 40
    concepts:
      - gcs_total
      - aki_creatinine
      - aki_urine_output

  derived_components:
    order: 50
    concepts:
      - aki
      - sofa_cardiovascular
      - sofa_cns
      - sofa_coagulation
      - sofa_liver
      - sofa_renal
      - sofa_respiratory

  derived_aggregates:
    order: 60
    concepts:
      - sofa

  icu_discharge:
    order: 90
    concepts:
      - icu_discharge

  hospital_discharge:
    order: 91
    concepts:
      - hospital_discharge
