"""Public Python API for the RICU -> OpenICU config converter.

This module mirrors the CLI workflow and is intended for scripts and notebooks.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .loader import load_concept_dict
from .mapper import RICUToOpenICUMapper, unsupported_report
from .models import GeneratedFile, UnsupportedItem
from .settings import (
    ConverterSettings,
    load_project_event_names,
    load_project_event_names_by_code_column,
)
from .writer import OpenICUYAMLWriter


@dataclass(frozen=True)
class GenerationPlan:
    """All YAML payloads and report entries generated by one conversion run."""

    files: list[GeneratedFile]
    unsupported: list[UnsupportedItem]
    report: dict


def build_generation_plan(
    *,
    concept_dict_path: str | Path,
    sources: list[str],
    settings_path: str | Path | None = None,
    openicu_config: str | Path | None = None,
    concepts: list[str] | set[str] | None = None,
    categories: list[str] | set[str] | None = None,
    include_derived: bool = False,
    complex_stubs: bool = False,
    complex_transformer: str = "open_icu.concepts.ricu_transformers.UnsupportedRICUTransformer",
    regex_prefix_mode: str | None = None,
    logical_columns_mode: str | None = None,
) -> GenerationPlan:
    """Build generated config payloads without writing them.

    Parameters are equivalent to the CLI options.
    """

    settings = ConverterSettings.from_file(settings_path)
    if regex_prefix_mode is not None:
        settings.regex_prefix_mode = regex_prefix_mode
    if logical_columns_mode is not None:
        settings.logical_columns_mode = logical_columns_mode

    inferred_by_code_column = {}
    if openicu_config is not None:
        inferred_table_events = load_project_event_names(openicu_config)
        for dataset, table_map in inferred_table_events.items():
            settings.event_names.setdefault(dataset, {}).update(table_map)
        inferred_by_code_column = load_project_event_names_by_code_column(openicu_config)

    concept_dict = load_concept_dict(concept_dict_path)
    mapper = RICUToOpenICUMapper(
        settings,
        inferred_events_by_code_column=inferred_by_code_column,
    )
    files = mapper.build_files(
        concept_dict,
        sources=sources,
        categories=set(categories) if categories else None,
        concept_keys=set(concepts) if concepts else None,
        include_derived=include_derived,
        complex_stubs=complex_stubs,
        complex_transformer=complex_transformer,
    )
    report = unsupported_report(mapper.unsupported)
    return GenerationPlan(files=files, unsupported=mapper.unsupported, report=report)


def write_generation_plan(
    plan: GenerationPlan,
    output_config: str | Path,
    *,
    overwrite: bool = False,
    report_path: str = "ricu_unsupported.yml",
) -> list[Path]:
    """Write a generated plan to an OpenICU-style config directory."""

    writer = OpenICUYAMLWriter(output_config, overwrite=overwrite)
    written = writer.write_files(plan.files)
    writer.write_report(plan.report, rel_path=report_path)
    return written


def convert(
    *,
    concept_dict_path: str | Path,
    output_config: str | Path,
    sources: list[str],
    settings_path: str | Path | None = None,
    openicu_config: str | Path | None = None,
    concepts: list[str] | set[str] | None = None,
    categories: list[str] | set[str] | None = None,
    include_derived: bool = False,
    complex_stubs: bool = False,
    overwrite: bool = False,
    complex_transformer: str = "open_icu.concepts.ricu_transformers.UnsupportedRICUTransformer",
    regex_prefix_mode: str | None = None,
    logical_columns_mode: str | None = None,
) -> GenerationPlan:
    """Build and write generated config files in one function call."""

    plan = build_generation_plan(
        concept_dict_path=concept_dict_path,
        sources=sources,
        settings_path=settings_path,
        openicu_config=openicu_config,
        concepts=concepts,
        categories=categories,
        include_derived=include_derived,
        complex_stubs=complex_stubs,
        complex_transformer=complex_transformer,
        regex_prefix_mode=regex_prefix_mode,
        logical_columns_mode=logical_columns_mode,
    )
    write_generation_plan(plan, output_config, overwrite=overwrite)
    return plan
