type: simple
mappings:
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (221906(//.*)?)
    columns:
      numeric_value: replace(rateuom == "mg/kg/min", rate * 1000, rate)
      text_value: col(text_value)
    filters:
      - drop_na(numeric_value)
