type: simple
mappings:
  - pattern:
      table: inputevents
      event: INFUSION_END
      code: (221749(//.*)?)
    columns:
      numeric_value: col(rate)
      text_value: col(text_value)
    filters:
      - rateuom == "mcg/kg/min"
      - drop_na(numeric_value)
      - numeric_value > 0
