name: endtidal_CO2
version: 1.0.0
unit: ['mmHg', 'mm Hg']

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (228640//EtCO2)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
