name: heart_rate
version: 1.0.0
unit: ['bpm', '/min']

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (220045//Heart Rate)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
