name: mean_arterial_pressure
version: 1.0.0
unit: ['mmHg', 'mm Hg']

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (220052//Arterial Blood Pressure mean|220181//Non Invasive Blood Pressure mean|225312//ART BP Mean)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
