name: temperature
version: 1.0.0
unit: ['C', '°C']

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (223762//Temperature Celsius)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: chartevents
      event: result
      code: (223761//Temperature Fahrenheit|224027//Skin Temperature)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
